### ISSUE TITLE
SRU_Compute_No_Kernel references an undefined variable

### ISSUE THREAD

**Issue by williamabrwolf** [pytorch/benchmark#10]
Sigh. Don't have time to submit a PR. Looks like `ncols`, used [here](https://github.com/pytorch/benchmark/blob/c33838af059e48741f0e68f2a187c6b44fdcee0a/benchmarks/sru.py#L458), is undefined.

**Comment by ezyang** [comment]
Thanks, we'll take a look.

**Comment by wconstab** [comment]
Cleaning up benchmark repo, closing old issues, please reopen if needed.
