### ISSUE TITLE
How to add an new backend?

### ISSUE THREAD

**Issue by zzpmiracle** [pytorch/benchmark#1046]
Hello, I want to add an new backend to run benchmark **without** modify this repo's code. In torchdynamo repo, I use @create_backend decorator to finish this, but I can't find suitable interface in this repo.

**Comment by xuzhao9** [comment]
Can you specify what backend you want to add? We automatically support all backends available in `torchdynamo.list_backends()` (https://github.com/pytorch/benchmark/blob/main/torchbenchmark/util/backends/torchdynamo.py#L16)

**Comment by xuzhao9** [comment]
We already support torchdynamo frontend, so if you have already added the BladeDISC backend for torchdynamo, you don't need to modify this repo, you can just use something like `--torchdynamo BladeDISC`, if you have already registered it in torchdynamo (i.e., BladeDISC is available in `torchdynamo.list_backends()`).

For your request `add an interface to register backends`, I still need some context. Do you mean you would like to run BladeDISC directly on eager mode, without torchscript or torchdynamo frontend, or do you mean you would like an option for torchscript to add backend?

**Comment by zzpmiracle** [comment]
Yes, we'd like to add backends just for torchscript now. 
> We can consider some torchdynamo-like interface here, e.g., use decorator to register new eager or torchscript backends.

Yeah, this would be fascinating for the ecology of compiler. And I think it's necessary when more backends want to use this benchmark repo.

**Comment by xuzhao9** [comment]
@zzpmiracle I created https://github.com/pytorch/benchmark/pull/1059 to make it easier to add more backends.

**Comment by zzpmiracle** [comment]
@xuzhao9 Thanks! I think it's very convinient now to add more backends. And maybe I can change other backends in this repo in this way later.
Thanks again!

**Comment by xuzhao9** [comment]
Closed by #1059
