### ISSUE TITLE
Add  huggingface diffuser models

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#1053]
https://github.com/huggingface/diffusers

**Comment by msaroufim** [comment]
Hi @xuzhao9 is this still something you're working on, was interested in adding #1444 and it'd be trivial to add if diffusers support was included

**Comment by xuzhao9** [comment]
I can work on an example to add instructpix2pix

**Comment by msaroufim** [comment]
That'd be super helpful thanks! I'll focus on LLAMA then

**Comment by xuzhao9** [comment]
Fixed by https://github.com/pytorch/benchmark/pull/1451
