### ISSUE TITLE
fambench_dlrm is very slow

### ISSUE THREAD

**Issue by jansel** [pytorch/benchmark#1106]
The following takes more than an hour:
```
./benchmarks/torchbench.py -dcuda -k fambench_dlrm --nothing -n100
```

This hurts time to signal a lot.

**Comment by xuzhao9** [comment]
Yeah I have also noticed that, the model is too large (~13G after `torch.save()`). However, this model represents internal use case and is still useful. I am thinking to add a variable `VERY_LARGE_MODEL=True` to the class, and users skip the large models when they want to get quick results.

What do you think?

**Comment by jansel** [comment]
IMO this model is slow enough that it is not useful.  We could put it behind a flag like you suggest, but I think then people just won't use it.

Yesterday I updated torchbench, did an overnight run (which usually takes a couple of hours) and by morning it was still stuck on `fambench_dlrm` for one of the baselines and I got zero result for the actual experiment.  That ruined my experiment and wasted time.  I killed the running experiment, deleted the model in my working tree, restarted the run, then got results in the afternoon.

Is there a way we could have a faster time-to-signal model that still represents the important patterns we want to test?  Is the pattern already well captured in the other dlrm model in torchbench?

**Comment by xuzhao9** [comment]
I see, we are planning to replace the current oss dlrm (which is old) with torchrec version to make it more representative. As a quick mitigation I will remove this model in the `models/` directory and put it in a separate directory for archive.
