### ISSUE TITLE
soft_actor_critic does not use the new gym API and crash on env initialization

### ISSUE THREAD

**Issue by Delaunay** [pytorch/benchmark#1271]
Gym deprecated the method `env.seed` and needs to use `env.reset(seed=seed)` instead

The method `end.seed` was removed in https://github.com/openai/gym/commit/3a8daafce113c6161190c0252c6a3a340cc38fd4#diff-8f3ae46be618d936b191b5f32bad0dcc4674ea5385bafb31a6c02840a43fe76aL196

**Comment by xuzhao9** [comment]
Fixed in https://github.com/pytorch/benchmark/pull/1272
