### ISSUE TITLE
Remove bloat from git repo

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#128]
These account for a large % of the repo size but aren't needed.  However, some work is needed before they can all be removed, and then the process of rewriting git history to clean the files up should be done all at once and carefully.  This issue can accumulate a wish list of files to delete, and at some point we can purge them all at once. 

demucs/results/* -- can be removed, not used by benchmark
Background_matting/sample_data -- apparently not used, another `ak` folder contains used data
yolov3/data --contains mini coco, which is also checked in under torchbenchmark/data, so that should be used instead

**Comment by xuzhao9** [comment]
This has been resolved as part of the Facebook internal integration process.
