### ISSUE TITLE
Is it possible to run with Cuda 11.8?

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/benchmark#1364]
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu118

**Comment by xuzhao9** [comment]
We haven't tested it on CUDA 11.8, but it should be runnable.

**Comment by johnnynunez** [comment]
It's strange because if I install cuda 11.8 torch not detected by script but with cuda11.6 binaries yes

**Comment by xuzhao9** [comment]
> 

Can I have the error messages?
Make sure you have installed the domain libraries, including torchvision, torchtext, and torchaudio.

**Comment by johnnynunez** [comment]
```
conda create -n torchbenchmark python=3.8
conda activate torchbenchmark
conda install -y git-lfs
conda install -y -c pytorch magma-cuda118
conda install pytorch torchvision torchtext torchaudio pytorch-cuda=11.8 -c pytorch-nightly -c nvidia
```
solved
