### ISSUE TITLE
Add torchvision maskrcnn (enable jit, dynamic shapes) 

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#137]
The 'maskrcnn-benchmark' model has already been added to the benchmark, but it doesn't easily JIT, and we want dynamic shape models to go through PE/TE.  

This model is known to jit compile, and should be added to the benchmark
https://github.com/pytorch/vision/blob/master/torchvision/models/detection/mask_rcnn.py
see this test for the exact configuration that is tested with JIT
https://github.com/pytorch/vision/blob/master/test/test_models.py#L68

ideally, reuse coco dataset artifacts that are checked in already from the other maskrcnn.

follow general instructions in[ ADDING_MODELS.md](https://github.com/pytorch/benchmark/blob/master/torchbenchmark/models/ADDING_MODELS.md)

**Comment by xuzhao9** [comment]
Added in https://github.com/pytorch/benchmark/pull/547, but it still doesn't jit

**Comment by xuzhao9** [comment]
Closed
