### ISSUE TITLE
enable running a model script directly 

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#138]
right now, you can't `python torchbenchmark/models/dlrm/__init__.py` becuase "ImportError: attempted relative import with no known parent package".  

how can the __main__ block in __init__.py be executed?  If it's possible we should write up the workaround in README, or else it would be nice to enable.

**Comment by Krovatkin** [comment]
I think this ` python -m torchbenchmark.models.BERT_pytorch.__init__` works pretty well now, but we should add it to `README.md`

**Comment by xuzhao9** [comment]
> I think this ` python -m torchbenchmark.models.BERT_pytorch.__init__` works pretty well now, but we should add it to `README.md`
The command works for the BERT_pytorch model, but when I am running it on other models, say "Background_Matting", the command returns nothing because there is no main function in the module: https://github.com/pytorch/benchmark/blob/master/torchbenchmark/models/Background_Matting/__init__.py
