### ISSUE TITLE
Print memory metrics by default

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#1387]
Let `run.py` print CPU and GPU peak memory information by default.

**Comment by FindHao** [comment]
some notes:

**Comment by xuzhao9** [comment]
1. Sounds good to me.
2. Also sounds fine, doesn't really matter.
3. Since we have added to `requirements.txt`, it should be good
4. The availability of dcgm is a problem because it requires setting up special permissions to performance counters, which might not be available everywhere (e.g. sudo not available or can't set the special option to nvidia kernel module)

**Comment by xuzhao9** [comment]
Closed by https://github.com/pytorch/benchmark/pull/1392
