### ISSUE TITLE
Https proxy comment in test.py

### ISSUE THREAD

**Issue by milutter** [pytorch/benchmark#140]
I am trying to run the benchmarks, but the benchmarks hangs when running `python test.py`. The script does not run and gets stuck somewhere. I discovered the comment in `test.py`

> Make sure to enable an https proxy if necessary, or the setup steps may hang.

What does that mean? What script does need the proxy for what?

**Comment by bertmaher** [comment]
The test script needs to be able to access the internet (on first run, at least) to download test data and the like.  So if you're inside a firewall you'll need a proxy server to get out.  This is a common setup for facebook engineers (hence the comment) but may not really apply to the rest of the world.

**Comment by wconstab** [comment]
@milutter were you able to get past the stuck issue?

**Comment by milutter** [comment]
Thanks for the help. I got it to partially work but it was just surprising to see that it is downloading something without an progress bar. I stopped using it because the test did not work easily and my need for benchmarking was not that great.
