### ISSUE TITLE
Modify fastNLP to work with latest and older torchtext releases

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#142]
torchtext 0.8.0 release moved AG_NEWS from datasets.experimental. to datasets.  fastNLP should be able to run under new and old torchtext for the sake of running historical builds, so we can check the torchtext version in the fastNLP __init__.py and conditionally import the right name.

**Comment by xuzhao9** [comment]
Cherry-picked [the fix](https://github.com/pytorch/benchmark/commit/ac7a531235509dea0cf7579d60aa62f7ba980172) to 0.1 branch
