### ISSUE TITLE
OOM for FP32 tests with PyTorch 20230102 cu118

### ISSUE THREAD

**Issue by FindHao** [pytorch/benchmark#1421]
The following models have OOM for `--precision fp32` when running with PyTorch nightly  20230102 cuda 11.8. 

inference:
alexnet, densenet121, mnasnet1_0, mobilenet_v2, mobilenet_v3_large, resnet152, resnet18, resnet50, resnext50_32x4d, squeezenet1_1

training:
hf_T5_base

**Comment by xuzhao9** [comment]
What is the hardware platform?
We probably just aim to cover the default precision and don't aim to cover fp32 on A100 40GB across all models.

**Comment by FindHao** [comment]
The GPU I tesetd is A100 40GB.

Yes. the OOM happens on cuda 11.8 with cudnn 8.7.0, but cuda 11.6  with cudnn 8.3.2 works well. The experiments are a little bit tricky. I'll reproduce the results and show more details later.

**Comment by xuzhao9** [comment]
What is the peak memory usage of CUDA 11.6+cudnn 8.3.2?
