### ISSUE TITLE
issues with userbenchmark/ddp_experiments/__init__.py

### ISSUE THREAD

**Issue by ShiboXing** [pytorch/benchmark#1486]
Hi everyone, 

the --timeout flag doesn't seem to work due to the hard coding here: https://github.com/pytorch/benchmark/blob/355dc8002ea89f2899cc048553d5975c2ea02954/userbenchmark/ddp_experiments/__init__.py#L220

The command I'm using is `python userbenchmark/ddp_experiments/__init__.py --ngpus 4 --distributed ddp --nodes 1 --cluster local --filter_models resnet50 --timeout 2`

Additionally, would it be better if the script leaves an option flag for the network interface name: https://github.com/pytorch/benchmark/blob/355dc8002ea89f2899cc048553d5975c2ea02954/userbenchmark/ddp_experiments/__init__.py#L374 ?

please correct if I'm not using the ddp benchmark correctly.

**Comment by ShiboXing** [comment]
Looks the timeout is for slurm job, is there any plan to support timeout for local?

**Comment by xuzhao9** [comment]
@wconstab Can you help answer this question?

**Comment by wconstab** [comment]
No plans per se, but happy to accept a PR to improve the script.  also cc @davidberard98

**Comment by davidberard98** [comment]
I can open a PR

**Comment by ShiboXing** [comment]
thanks everyone!
