### ISSUE TITLE
Torchtext 20230324 should depend on torchdata20230224, not torchdata20230223

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#1504]
$ pip install torchtext-0.15.1.dev20230324+cpu-cp310-cp310-linux_x86_64.whl
Processing ./torchtext-0.15.1.dev20230324+cpu-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: tqdm in /home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages (from torchtext==0.15.1.dev20230324+cpu) (4.64.1)
ERROR: Could not find a version that satisfies the requirement torchdata==0.7.0.dev20230323 (from torchtext) (from versions: 0.3.0a0, 0.3.0a1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0)
ERROR: No matching distribution found for torchdata==0.7.0.dev20230323

**Comment by xuzhao9** [comment]
Is there a check of nightly releases?
```
$ pip install --pre  torch torchvision torchtext torchaudio -f https://download.pytorch.org/whl/nightly/cu117/torch_nightly.html
Successfully installed torch-2.1.0.dev20230324+cu117 torchaudio-2.1.0.dev20230324+cu117 torchtext-0.6.0 torchvision-0.16.0.dev20230324+cu117
```

The torchtext release is broken.

**Comment by atalman** [comment]
This is resolved: https://github.com/pytorch/text/actions/runs/4557436885/jobs/8039077386#step:10:301
Since it's nightly occasionally we observe errors in nightly builds. Hence it falls back to previous builds

**Comment by atalman** [comment]
closing this as per above comment, feel free to reopen if you see this issue tomorrow

**Comment by xuzhao9** [comment]
Reopening because torchtext still has build issues

**Comment by weiwangmeta** [comment]
pip3 install --no-cache-dir --pre torchtext --index-url https://download.pytorch.org/whl/nightly/cu117
Looking in indexes: https://download.pytorch.org/whl/nightly/cu117                                                                                                                                                            
Collecting torchtext                                                                                           
  Downloading https://download.pytorch.org/whl/nightly/torchtext-0.15.1.dev20230330%2Bcpu-cp310-cp310-linux_x86_64.whl (2.0 MB)                                  
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 289.5 MB/s eta 0:00:00                                                                                                                                               
Collecting tqdm                                                                                                                                                                                                               
  Downloading https://download.pytorch.org/whl/nightly/tqdm-4.64.1-py2.py3-none-any.whl (78 kB)                                                                                                                               
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 230.6 MB/s eta 0:00:00                                                                                                                                             
**Collecting torchdata==0.7.0.dev20230329**                                                                                                                                                                                       
  Downloading https://download.pytorch.org/whl/nightly/torchdata-0.7.0.dev20230329-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)   
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 339.0 MB/s eta 0:00:00
Requirement already satisfied: requests in /fsx/users/weiwangmeta/conda/envs/test-tb-nightly/lib/python3.10/site-packages (from torchtext) (2.28.1)
Requirement already satisfied: numpy in /fsx/users/weiwangmeta/conda/envs/test-tb-nightly/lib/python3.10/site-packages (from torchtext) (1.24.1)
Collecting torch==2.1.0.dev20230329            
  Downloading https://download.pytorch.org/whl/nightly/cu117/torch-2.1.0.dev20230329%2Bcu117-cp310-cp310-linux_x86_64.whl (1833.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 356.3 MB/s eta 0:00:00


For some reason torchdata 20230329 was collected first.

**Comment by weiwangmeta** [comment]
We probably need to delay TorchText nightly binary build to give TorchData sometime. 

cc @atalman

**Comment by weiwangmeta** [comment]
Manually re-running torchtext binary build again. Dependency on torchdata becomes 03/30/2023. 
https://github.com/pytorch/text/actions/runs/4563851198/jobs/8062310373#step:15:42

**Comment by xuzhao9** [comment]
I can confirm this problem has been fixed, thanks @weiwangmeta  and @atalman !
