### ISSUE TITLE
GAT model is broken

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#1552]
From https://github.com/pytorch/benchmark/actions/runs/4684546103/jobs/8308885461?pr=1549 we found the gat model is broken with error message `ImportError: 'NeighborSampler' requires either 'pyg-lib' or 'torch-sparse'`.

Can you help take a look, @yanbing-j ?

**Comment by yanbing-j** [comment]
Sure. I'm investigating.

**Comment by yanbing-j** [comment]
May I ask if the error comes from recent days in CI check? If so,the error probably is the incompatibility between pytorch nightly and dependency libraries from https://data.pyg.org/whl/torch-2.0.0+cu117.html.

**Comment by xuzhao9** [comment]
> May I ask if the error comes from recent days in CI check? If so,the error probably is the incompatibility between pytorch nightly and dependency libraries from https://data.pyg.org/whl/torch-2.0.0+cu117.html.

Yes, the error comes from recent days in CI check. If the dependency library is unstable, we consider move the model from `models/` directory to the [canary_models/](https://github.com/pytorch/benchmark/tree/main/torchbenchmark/canary_models) directory, so that CI won't check their status. What do you think?

**Comment by yanbing-j** [comment]
> > May I ask if the error comes from recent days in CI check? If so,the error probably is the incompatibility between pytorch nightly and dependency libraries from https://data.pyg.org/whl/torch-2.0.0+cu117.html.
> 
> Yes, the error comes from recent days in CI check. If the dependency library is unstable, we consider move the model from `models/` directory to the [canary_models/](https://github.com/pytorch/benchmark/tree/main/torchbenchmark/canary_models) directory, so that CI won't check their status. What do you think?

Yes, I think moving the models to `canary_models` is a better choice now. I have connected with PyG maintainer, he confirmed that the wheel is compiled based on PyTorch 2.0 and could not be adaptive to pytorch nightly.

**Comment by xuzhao9** [comment]
> > > May I ask if the error comes from recent days in CI check? If so,the error probably is the incompatibility between pytorch nightly and dependency libraries from https://data.pyg.org/whl/torch-2.0.0+cu117.html.
> > 
> > 
> > Yes, the error comes from recent days in CI check. If the dependency library is unstable, we consider move the model from `models/` directory to the [canary_models/](https://github.com/pytorch/benchmark/tree/main/torchbenchmark/canary_models) directory, so that CI won't check their status. What do you think?
> 
> Yes, I think moving the models to `canary_models` is a better choice now. I have connected with PyG maintainer, he confirmed that the wheel is compiled based on PyTorch 2.0 and could not be adaptive to pytorch nightly.

Let's move it to the `canary_models` then, can you help create a PR to do that?

**Comment by yanbing-j** [comment]
Sure. @xuzhao9
