### ISSUE TITLE
How to execute with docker?

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/benchmark#1707]
I'm using ARG BASE_IMAGE=ghcr.io/pytorch/torchbench:latest 
but I am having problems with this container.
or should use ghcr.io/pytorch:pytorch-nightly or [ghcr.io/pytorch:pytorch-nightly](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)

**Comment by xuzhao9** [comment]
`ghcr.io/pytorch/torchbench:latest` is the container we use. Can I have the concrete problems with this container?

**Comment by johnnynunez** [comment]
> `ghcr.io/pytorch/torchbench:latest` is the container we use. Can I have the concrete problems with this container?

so pulling from this image, can I directly put this in my personal computer?
pytest test_bench.py --benchmark-autosave --ignore_machine_config

**Comment by xuzhao9** [comment]
You can try this command.
Another option is to try `python run.py resnet50 -d cpu` to test individual model run.

**Comment by johnnynunez** [comment]
> You can try this command. Another option is to try `python run.py resnet50 -d cpu` to test individual model run.

it's for review gpu's, for example I have 3090, 4090, and rtx a6000 ada

**Comment by johnnynunez** [comment]
> You need to run the docker with `--gpus all`, and try
> 
> ```
> python run.py resnet50 -d cuda
> ```
> 
> Note that since we don't test on these hardware (we only test on NVidia A10G and A100 GPU platforms), you may encounter issues such as CUDA OOM.

and if I would like to test all models? And high memory use like rtx ada a6000?
Is it running like
```bash
python3 run_benchmark.py model-stableness -d cuda
```

**Comment by xuzhao9** [comment]
Can you please try the following command:
```
python run_benchmark.py torch-nightly -d cuda -t train,eval
```

**Comment by johnnynunez** [comment]
> Can you please try the following command:
> 
> ```
> python run_benchmark.py torch-nightly -d cuda -t train,eval
> ```
> 
> The output will be a json file as `.userbenchmark/torch-nightly/metrics-YYmmddHHMMSS.json`

Is the batch size calculated automatically?
For example, take advantage of the 48gb of the rtxa6000 and see if there are differences with the 4090 for example.

**Comment by xuzhao9** [comment]
> Is the batch size calculated automatically? For example, take advantage of the 48gb of the rtxa6000 and see if there are differences with the 4090 for example.

It uses the default batch size setup in the model code and metadata.yaml. The determination of the default batch size is a complex process, see: https://github.com/pytorch/benchmark/blob/main/torchbenchmark/util/model.py#L186

Some models don't allow customizing batch size, for those, we don't allow user changing the batch size.
Otherwise, we will use the default batch size from either upstream model repo or research paper for train.
For inference, we use the largest batch size possible on A100 by default.

**Comment by johnnynunez** [comment]
> This is the CUDA OOM error. The direct cause is small GPU memory size. It could be the model is too large or the model input size is too large. In the latter case, you can try use a smaller batch size.

Where do you change this?

**Comment by xuzhao9** [comment]
> > This is the CUDA OOM error. The direct cause is small GPU memory size. It could be the model is too large or the model input size is too large. In the latter case, you can try use a smaller batch size.
> 
> Where do you change this?

Different models have different default batch sizes. For `hf_T5_base` train test, you can change it at https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/hf_T5_base/__init__.py#L8

**Comment by johnnynunez** [comment]
> > > This is the CUDA OOM error. The direct cause is small GPU memory size. It could be the model is too large or the model input size is too large. In the latter case, you can try use a smaller batch size.
> > 
> > 
> > Where do you change this?
> 
> Different models have different default batch sizes. For `hf_T5_base` train test, you can change it at https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/hf_T5_base/__init__.py#L8

new error:
Running TorchBenchModelConfig(name='torchrec_dlrm', test='train', device='cuda', jit=False, batch_size=None, extra_args=[], extra_env=None) ...components._impl.workers.subprocess_rpc.ChildTraceException: Traceback (most recent call last):
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torch/_ops.py", line 709, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator fbgemm::jagged_2d_to_dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/benchmark/components/_impl/workers/subprocess_rpc.py", line 482, in _run_block
    exec(  # noqa: P204
  File "<subprocess-worker>", line 44, in <module>
  File "<subprocess-worker>", line 14, in _run_in_worker_f
  File "/opt/conda/envs/torchbench/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/benchmark/torchbenchmark/models/torchrec_dlrm/__init__.py", line 7, in <module>
    from .data.dlrm_dataloader import get_dataloader
  File "/workspace/benchmark/torchbenchmark/models/torchrec_dlrm/data/dlrm_dataloader.py", line 13, in <module>
    from torchrec.datasets.criteo import (
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/distributed/__init__.py", line 36, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/distributed/model_parallel.py", line 20, in <module>
    from torchrec.distributed.planner import (
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/distributed/planner/__init__.py", line 22, in <module>
    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/distributed/planner/planners.py", line 19, in <module>
    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/distributed/planner/constants.py", line 10, in <module>
    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torchrec/distributed/embedding_types.py", line 14, in <module>
    from fbgemm_gpu.split_table_batched_embeddings_ops_training import EmbeddingLocation
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 21, in <module>
    from . import _fbgemm_gpu_docs  # noqa: F401, E402
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 19, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/opt/conda/envs/torchbench/lib/python3.10/site-packages/torch/_ops.py", line 713, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

**Comment by xuzhao9** [comment]
torchrec_dlrm requires only works on torch nightly release, we are consider moving it to the canary_models. Maybe just try skip this specific model.

**Comment by johnnynunez** [comment]
> torchrec_dlrm requires only works on torch nightly release, we are consider moving it to the canary_models. Maybe just try skip this specific model.

I’m using torch nightly with cuda 12.1. Well I will try to skip. Thanks

**Comment by xuzhao9** [comment]
> > torchrec_dlrm requires only works on torch nightly release, we are consider moving it to the canary_models. Maybe just try skip this specific model.
> 
> I’m using torch nightly with cuda 12.1. Well I will try to skip. Thanks
> 
> ```
> python run_benchmark.py torch-nightly -d cuda -t train,eval
> ```
> 
> https://github.com/johnnynunez/pytorch_benchmark/blob/main/docker/Dockerfile

If so, you can try installing the fbgemm_gpu_nightly package, or trying to recompile the package against the pytorch version you are using.

**Comment by johnnynunez** [comment]
> > > torchrec_dlrm requires only works on torch nightly release, we are consider moving it to the canary_models. Maybe just try skip this specific model.
> > 
> > 
> > I’m using torch nightly with cuda 12.1. Well I will try to skip. Thanks
> > ```
> > python run_benchmark.py torch-nightly -d cuda -t train,eval
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/johnnynunez/pytorch_benchmark/blob/main/docker/Dockerfile
> 
> The error means the fbgemm_gpu_nightly package version you are using is not compatible to the torch nightly version.
> 
> If so, you can try installing the fbgemm_gpu_nightly package, or to recompile the package against the pytorch version you are using. If it still doesn't work, try skip it. https://github.com/pytorch/fbgemm

In case of skip, which file is it?

**Comment by xuzhao9** [comment]
The `*_latency` metric is the median per-iteration latency of the test in ms, `*_cmem` is the peak CPU memory, and `*_gmem` is the peak GPU memory, both in GB.

**Comment by xuzhao9** [comment]
> 

`score.py` is deprecated. Can you try running `python run_benchmark.py torch-nightly -c v3-cuda-tests.yaml`? You might need to delete the torchrec_dlrm model from the config: https://github.com/pytorch/benchmark/blob/main/userbenchmark/torch-nightly/v3-cuda-tests.yaml

**Comment by johnnynunez** [comment]
> python run_benchmark.py torch-nightly -c v3-cuda-tests.yaml

Nice, I will try to help you, and add the recent networks and improvement in the future, sorry with spam, but I'm interested because is the best repository with the recent networks, and I have a lot of hardware to review. I will investigate for example calculate the batch automatically...

**Comment by xuzhao9** [comment]
@johnnynunez Thanks, please consider writing a userbenchmark for calculating the bach sizes automatically, thanks!
