### ISSUE TITLE
Add Segment Anything

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/benchmark#1708]
https://segment-anything.com/

**Comment by xuzhao9** [comment]
It is already added: https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/sam/__init__.py

**Comment by johnnynunez** [comment]
> It is already added: https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/sam/__init__.py

thanks, https://github.com/pytorch/benchmark/blob/main/torchbenchmark/score/configs/v1/config-v1.md the list is outdated
