### ISSUE TITLE
install.py installs datasets for all models, even if model to install is specified

### ISSUE THREAD

**Issue by ezyang** [pytorch/benchmark#1717]
Steps to reproduce: Run `python install.py asdfjksdfd`

**Comment by xuzhao9** [comment]
Some models are sharing the same input sets like coco2017, and if all models need to specify their input data, we need to think about how to avoid downloading the same input data files repeatedly.

Currently https://github.com/pytorch/benchmark/pull/1734 only checks the existence of the file and directories without checking their integrity, which can be future work.
