### ISSUE TITLE
Comparation between compile and not compile in pytorch 2.0?

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/benchmark#1719]

**Comment by xuzhao9** [comment]
The compiled metrics are available here: https://hud.pytorch.org/benchmark/compilers

**Comment by johnnynunez** [comment]
> The compiled metrics are available here: https://hud.pytorch.org/benchmark/compilers

is it possible to have this in loca?

**Comment by xuzhao9** [comment]
This website requires different infra services, see: https://github.com/pytorch/test-infra/tree/main/torchci

It is possible but won't be straightforward to deploy locally.
