### ISSUE TITLE
Error: sometimes all packages are not build on the same date

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/benchmark#1728]
Hi,
for example last build torch is compiled 20230610 while torchdata is compiled in 20230608. How to force it on the same date for example 20230608?

**Comment by xuzhao9** [comment]
It is possible that torch compiles successfully on 20230610 but torchdata/torchvision/torchtext/torchaudio does not. In this case, you need to use the torchbench docker: https://github.com/orgs/pytorch/packages/container/package/torchbench

For example, the [dev20230608](https://github.com/orgs/pytorch/packages/container/torchbench/99931534?tag=dev20230608) tag guarantees that all torch* packages are on 20230608.
