### ISSUE TITLE
[Question][Background_Matting] Unused intermediate result `multi_feat`.

### ISSUE THREAD

**Issue by BowenBao** [pytorch/benchmark#1768]
Observe `multi_feat` is unused and not returned. Should it be removed or is it a bug in the implementation?

https://github.com/pytorch/benchmark/blob/2ea018e9b6680e19d5ebb3267d6ceb6d14271dbc/torchbenchmark/models/Background_Matting/networks.py#L97-L111

**Comment by xuzhao9** [comment]
This issue is from the upstream model code: https://github.com/senguptaumd/Background-Matting/blob/master/networks.py#L97

We are open to fix it, if you create a PR in the upstream repo, and reference to the upstream PR in the pytorch/benchmark PR.
