### ISSUE TITLE
install.py fails because of pyworld

### ISSUE THREAD

**Issue by MatPoliquin** [pytorch/benchmark#1772]
python install.py fails because of pyworld

```
running setup for /home/mat/github/benchmark/torchbenchmark/models/timm_resnest...OK
running setup for /home/mat/github/benchmark/torchbenchmark/models/timm_vision_transformer...OK
running setup for /home/mat/github/benchmark/torchbenchmark/models/timm_vision_transformer_large...OK
running setup for /home/mat/github/benchmark/torchbenchmark/models/timm_vovnet...OK
running setup for /home/mat/github/benchmark/torchbenchmark/models/tts_angular...FAIL
```

```
File "/home/mat/miniconda3/envs/torchbenchmark/lib/python3.10/json/encoder.py", line 179, in default
          raise TypeError(f'Object of type {o.__class__.__name__} '
      TypeError: Object of type PosixPath is not JSON serializable
```

Note:
When manually installing pyworld "pip install pyworld" I get the same error:

This problem seems specific to pyworld but anybody met this issue as well?

Specs:
Ubuntu 22.04 - WSL2
Python 3.10.12
benckmark commit: [7f71d89](https://github.com/angular/angular/commit/7f71d89c9ac0e3f66ff86a0bbbca452fb0d495cc)

**Comment by MatPoliquin** [comment]
Solved it using:
```
pip install pyworld --no-build-isolation
```

**Comment by xuzhao9** [comment]
After searching the code base, pyworld is not really being used by this model.
Maybe just try removing pyworld from requirements.txt file: https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/tts_angular/requirements.txt#L11
