### ISSUE TITLE
how to run torchbenchmark in dynamo mode

### ISSUE THREAD

**Issue by Godlovecui** [pytorch/benchmark#1825]
Hi,
 1. I want to test benchmark in dynamo mode, how can I run test_bench.py script?
 2. When I add code:
 `self.model = torch.compile(self.model)`
   in BERT_pytorch __init__.py, then run:
`pytest test_bench.py -k "test_train[BERT_pytorch-cuda-eager]" --ignore_machine_config --benchmark-autosave`, it raises below errors:
![image](https://github.com/pytorch/benchmark/assets/68674291/e92121ae-aa89-4558-bff3-17ee3ec10213)
how can I fix it? Thank you for you help~ @ezyang @orionr @romovpa @kostmo @zdevito

**Comment by xuzhao9** [comment]
`test_bench.py` does not support running in dynamo mode.
To run a model in dynamo mode, try:
```
python run.py BERT_pytorch -d cuda -t train --torchdynamo inductor
```

**Comment by Godlovecui** [comment]
> `test_bench.py` does not support running in dynamo mode. To run a model in dynamo mode, try:
> 
> ```
> python run.py BERT_pytorch -d cuda -t train --torchdynamo inductor
> ```

OK, I see. Thank you for your help. @xuzhao9
