### ISSUE TITLE
Design the interface to support dynamic shapes and multiple batches.

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#1828]
By default, we should keep the consistent behaviour where each train or eval test runs only a single static batch.

Optionally, we should think about how to support multiple batches and let user set their preferred input streams for benchmarking.

My brief thoughts on how to design the interface:

`iter = self.get_input_iter() -> InputIterator`: return an iterator of input data, if max_batch is set, then len(iter) = max_batch, otherwise, return an iterator that will infinitely return some data batch (e.g. repeatly return the same batch).

cc @ezyang @janeyx99 @msaroufim @FindHao  for feedbacks

**Comment by ezyang** [comment]
One thing I want to mention is that we also have to carefully review the input generation mechanism. torchrec_dlrm, in particular, doesn't actually generate inputs with varying sizes!

Also for my purposes, I don't need a fancy input distribution, I just need to be able to hit my model with a bunch of different unique shapes.

**Comment by ezyang** [comment]
I just mean upstream bugs like https://github.com/pytorch/torchrec/pull/1338

Can't take the dataset generators at their word, gotta make sure they actually work

**Comment by xuzhao9** [comment]
The interface `get_input_iter()` has been added, need to test the input data generator is indeed working by unit tests.
