### ISSUE TITLE
Benchmarks leak files

### ISSUE THREAD

**Issue by jansel** [pytorch/benchmark#186]
I observed that when you run benchmarks many files are created in the current working directory.  This is bad because:
1) It may increases benchmark variance because disk access can have less predictable performance
2) It it subjectively ugly/messy

Reproduce with:
```
rm -f Video_data_train_processed.csv labels.json results.png results.txt train_batch0.jpg checkpoints/*
pytest test.py
ls Video_data_train_processed.csv labels.json results.png results.txt train_batch0.jpg checkpoints/*
```

Actual output of `ls`
```
labels.json
results.png
results.txt
train_batch0.jpg
Video_data_train_processed.csv

checkpoints/horse2zebra:
loss_log.txt
train_opt.txt
web

checkpoints/horse2zebra_pretrained:
test_opt.txt
```

Desired output of `ls`:  empty with many "No such file or directory" errors

**Comment by xuzhao9** [comment]
Closed by https://github.com/pytorch/benchmark/pull/792
