### ISSUE TITLE
Add TorchBench to HUD and Run Periodically

### ISSUE THREAD

**Issue by atalman** [pytorch/benchmark#1893]

**Comment by xuzhao9** [comment]
It would be great if we could add a simple dashboard that covers all userbenchmarks through fetching data from S3.

**Comment by xuzhao9** [comment]
TODO:
1. Add pytorch version date to userbenchmarks so that we can track the commits by their dates
2. Update the dashboard and Rockset query to track the metrics by date

**Comment by xuzhao9** [comment]
Fixed by https://github.com/pytorch/test-infra/pull/4743
