### ISSUE TITLE
CI: No space left on device error

### ISSUE THREAD

**Issue by msaroufim** [pytorch/benchmark#1925]
https://github.com/pytorch/benchmark/actions/runs/6279881658/job/17056289916?pr=1921

Showing up here https://github.com/pytorch/benchmark/actions/runs/6279881658/job/17056289916?pr=1921

**Comment by xuzhao9** [comment]
The runner is A10G, which uses AWS linux.g5.4xlarge.nvidia.gpu type instance.

@malfet Do you think we could increase the disk size for this type of runner?

**Comment by malfet** [comment]
@xuzhao9 depends on how much disk space we might need. Perhaps we can create a specific runner type for torchbench runs if we need a really large disk space...

**Comment by xuzhao9** [comment]
@malfet I use this command to get the docker size:
```
$ docker manifest inspect -v ghcr.io/pytorch/torchbench:latest| grep size | awk -F ':' '{sum+=$NF} END {print sum}'| numfmt --to=iec-i
27Gi
```
