### ISSUE TITLE
benchmarks/dynamo/common.py should be identical to one in core

### ISSUE THREAD

**Issue by msaroufim** [pytorch/benchmark#1934]
I noticed this file was checked in https://github.com/pytorch/benchmark/blob/main/userbenchmark/dynamo/common.py

This is a fork of the equivalent file in core, `common.py` changes a lot so it might best if we package up the upstream `common.py` into its own package so code will be identical

**Comment by xuzhao9** [comment]
Currently this is blocked by an internal sync ShipIt bug, will continue working on this after the bug is resolved.

**Comment by xuzhao9** [comment]
Fixed by https://github.com/pytorch/benchmark/pull/1956
