### ISSUE TITLE
Speech_transformer issue

### ISSUE THREAD

**Issue by Aswin-coder** [pytorch/benchmark#2023]
I am trying to run the speech transformer model, but if I run it is displaying as "No hypothesis, Finish decoding"
1. Is there any way to fix it?
2. Can I pass my own wav audio file as input and predict it?

**Comment by Aswin-coder** [comment]
@davidberard98 can you help me please?

**Comment by davidberard98** [comment]
can you provide more details about how to reproduce the issue

**Comment by Aswin-coder** [comment]
> can you provide more details about how to reproduce the issue

1. I cloned the repo
2. python install.py model=speech transformer
3. python run.py -d cpu -t eval

**Comment by davidberard98** [comment]
are you missing the underscore in the commands?

2. `python install.py speech_transformer`
3. `python run.py speech_transformer -d cpu -t eval`

**Comment by Aswin-coder** [comment]
> are you missing the underscore in the commands?
> 
> 2. `python install.py speech_transformer`
> 3. `python run.py speech_transformer -d cpu -t eval`

Thats not an issue, model working fine but prediction is not working
<img width="960" alt="Screenshot 2023-11-01 180338" src="https://github.com/pytorch/benchmark/assets/61832161/558bf1b7-18d5-44eb-ad3d-d3553807691b">

**Comment by xuzhao9** [comment]
@Aswin-coder The goal of TorchBench core models is to just run a single batch with one iteration, it does not run end-2-end model, therefore it can't produce e2e metrics such as prediction.
