### ISSUE TITLE
simple-gpt usage and requirements

### ISSUE THREAD

**Issue by jinsong-mao** [pytorch/benchmark#2026]
Hi folks，

many thanks for this great work, I am at the very beginning stage of using torchbench, I want to try simple_gpt, looks it's different from nanogpt, I can't run it successfully based on the instructions of https://github.com/pytorch/benchmark/blob/main/README.md,  BTW, there is one command: https://github.com/pytorch/benchmark/pull/1867, but this command looks needs to be run on pytorch repo,  I am confused here.
1, what's the difference between torchbench and pytorch/benchmark?
2, what's the necessary's step/pre-request to run simple_gpt model?

looking forward to get feedback from you, 

thanks again.

**Comment by xuzhao9** [comment]
See my answers below:

1. `pytorch/benchmark` is used by `pytorch/pytorch` in its CI workflows. The PyTorch team uses the `torchbench.py` as a customized benchmark driver to implement their own features.
2. To run the simple_gpt model:
   a. Install torch, torchvision, and torchaudio nightly packages
   b. git clone the pytorch/pytorch directory and cd into it.
   b. Run the command `python benchmarks/dynamo/torchbench.py -d cuda --output-directory=benchmark_logs --output=performance.csv --inference --performance --timing --print-memory --multiprocess --nothing --only simple_gpt`

**Comment by jinsong-mao** [comment]
thanks Xu zhao,  it's much clear. 
BTW,  regarding to run simple_gpt,  is multi_gpu the basic requirement or can we run it with single gpu?

Best Regrads

**Comment by xuzhao9** [comment]
@jinsong-mao No, currently it requires multi_gpu. cc the model owner on more details @xmfan

**Comment by xmfan** [comment]
You can run `simple_gpt` with single gpu using the command in the linked PR, provided your GPU has enough memory. You can ignore the warning message:
```
WARNING:common:The use multiprocess flag is set but there are <= 1 devices available.
```

Note that this version of simple_gpt does not contain any model weights, nor the code to load them

**Comment by jinsong-mao** [comment]
got it, thanks, @xuzhao9 @xmfan
