### ISSUE TITLE
backend for --torchdynamo selection

### ISSUE THREAD

**Issue by jinsong-mao** [pytorch/benchmark#2029]
Hi  I am trying to run compilation of --torchdynamo with different backends, there are lot's of options:
[--torchdynamo {aot_eager,aot_eager_decomp_partition,aot_eager_default_partitioner,aot_torchxla_trace_once,aot_torchxla_trivial,aot_ts,cudagraphs,dynamo_accuracy_minifier_backend,dynamo_minifier_backend,eager,eager_debug,inductor,non_leaf_compile_error_TESTING_ONLY,onnxrt,openxla,openxla_eval,pre_dispatch_eager,relu_accuracy_error_TESTING_ONLY,relu_compile_error_TESTING_ONLY,relu_runtime_error_TESTING_ONLY,torchxla_trace_once,torchxla_trivial,ts,tvm}]

most of them is the first time to heard for me,  could u share/provide some doc/guidelines on how to understand its difference?

Thanks

**Comment by xuzhao9** [comment]
They are defined at: https://github.com/pytorch/pytorch/tree/9a909891212a73cdeed9ef379ac6d0fbe2b796db/torch/_dynamo/backends
