### ISSUE TITLE
how to get the memory test job

### ISSUE THREAD

**Issue by GuWei007** [pytorch/benchmark#2094]
https://arxiv.org/pdf/2304.14226.pdf  the paper says torchbench can do memory test， but I can‘t find any test jobs for memory test

https://github.com/pytorch/benchmark/actions

**Comment by GuWei007** [comment]
https://github.com/pytorch/pytorch/pull/85447   the paper says this issue was found by torchbench, can you please help me find the test job ?

**Comment by xuzhao9** [comment]
@GuWei007 The test job was on CircleCI: https://app.circleci.com/pipelines/github/pytorch/benchmark/5273/workflows/8792c508-526d-4b42-af90-0e76ec818d64/jobs/5423. Now it has been replaced by GitHub Actions.

We could test the following memory metrics:
1. Watch for CUDA memory leak. https://github.com/pytorch/benchmark/blob/main/torchbenchmark/__init__.py#L512
2. Peak CPU and GPU memory usage: https://github.com/pytorch/benchmark/blob/main/torchbenchmark/util/experiment/metrics.py#L52

**Comment by GuWei007** [comment]
I want to understand the testing mechanism of memory metrics， can you show me the test job code,   maybe lilke this https://github.com/pytorch/benchmark/tree/main/.github/workflows ?

**Comment by GuWei007** [comment]
As mentioned in the paper, I would like to understand which models were tested, what the thresholds were, how the testing cycles and frequencies were arranged, and how the test cases were designed. I work as an engineer at an AI chip manufacturer, and I'd like to learn from your testing mechanism. Thank you very much.

**Comment by xuzhao9** [comment]
@GuWei007 
I can only briefly answer your questions here.
The test is done everyday on the latest PyTorch nightly build, the models tested are in https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models, the threshold is set here: https://github.com/pytorch/benchmark/blob/main/userbenchmark/torch-nightly/regression_detector.py#L4.
The test job code is at https://github.com/pytorch/benchmark/blob/main/userbenchmark/torch-nightly/run.py

**Comment by GuWei007** [comment]
Thanks very much
