### ISSUE TITLE
WSL machine_config.py trouble because of intel_pstate/no_burbo file

### ISSUE THREAD

**Issue by lwk8891** [pytorch/benchmark#2172]
Ubuntu 22.04.3 LTS WSL Windows 11 Home 23H2
CUDA 12.3
13th Intel Core(TM) Core(TM) i9-13900H

I executed the following command to test benchmark:

pytest test_bench.py --benchmark-autosave

It occured the error:

Exit: [Errno 2] No such file or directory: '/sys/devices/system/cpu/intel_pstate/no_turbo'
See README.md for machine tuning script usage, or use --ignore_machine_config
! _pytest.outcomes.Exit: [Errno 2] No such file or directory: '/sys/devices/system/cpu/intel_pstate/no_turbo'
See README.md for machine tuning script usage, or use --ignore_machine_config !

I read README.md and try to configure my CPU informations by executing

sudo $(which python) torchbenchmark/util/machine_config.py --configure

but it occured error as following:

Write 1 to /sys/devices/system/cpu/intel_pstate/no_turbo
Traceback (most recent call last):
  File "/home/wglee/apps/benchmark/torchbenchmark/util/machine_config.py", line 315, in <module>
    set_intel_no_turbo_state(1)
  File "/home/wglee/apps/benchmark/torchbenchmark/util/machine_config.py", line 32, in set_intel_no_turbo_state
    write_sys_file(turbo_file, str(state))
  File "/home/wglee/apps/benchmark/torchbenchmark/util/machine_config.py", line 24, in write_sys_file
    with open(sysfile, 'w') as f:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/system/cpu/intel_pstate/no_turbo'

This error message means that the "sys/device/system/cpu/intel_pstate/no_turbo" file is nessesary, but my system doesn't have this. How can I solve this problem?

**Comment by xuzhao9** [comment]
Our machine config only applies to our CI machine, which is an AWS g4dn.metal instance. It comes with Intel(R) Xeon(R) Platinum 8259CL CPU and NVIDIA T4 GPU. Therefore, if your CPU does not support no_turbo, our machine config does not work. Please add `--ignore_machine_config ` to your command.
