### ISSUE TITLE
Reduce the size of the docker image

### ISSUE THREAD

**Issue by FindHao** [pytorch/benchmark#2218]
I noticed that the Docker image is significantly large.

The base image `ghcr.io/actions/actions-runner:latest` is about 1GB and the benchmark folder is about 9GB, but the whole torchbench image is over 40GB. 

Each `RUN` command in the [gcp-a100-runner-dind.dockerfile](https://github.com/pytorch/benchmark/blob/main/docker/gcp-a100-runner-dind.dockerfile) creates a layer during the Docker image building process. This could be a contributing factor to the image's size. Perhaps we could merge all commands into a single script or use && to chain them together, effectively reducing the number of layers.

**Comment by xuzhao9** [comment]
The docker image contains both CUDA 11.8 and 12.1 runtime for release testing (needs to compare the performance of 2 CUDA versions). I suspect that is the main source of image size bloating.

I am wondering how much does reducing the number of layers help in this case?

**Comment by FindHao** [comment]
I see. It looks like only several GBs, maybe 1 or 2,  we can reduce via reducing extra laybers.
