### ISSUE TITLE
Reason for chosing `data point: i = 20, size = 1048576` for pyhpc benchmarks

### ISSUE THREAD

**Issue by Abhishekghosh1998** [pytorch/benchmark#2237]
For pyhpc_equation_of_state:
https://github.com/pytorch/benchmark/blob/3f146bbe7fdd65c6f4490993a8e0fa78c4465f37/torchbenchmark/models/pyhpc_equation_of_state/__init__.py#L31C5-L35C33
```python
class Model(BenchmarkModel):
    task = OTHER.OTHER_TASKS
    # Original size: [2 ** i for i in range(12, 23, 2)
    # Source: https://github.com/dionhaefner/pyhpc-benchmarks/blob/650ecc650e394df829944ffcf09e9d646ec69691/run.py#L25
    # Pick data point: i = 20, size = 1048576
    DEFAULT_EVAL_BSIZE = 1048576
    CANNOT_SET_CUSTOM_OPTIMIZER = True
```
---

For  pyhpc_turbulent_kinetic_energy:
https://github.com/pytorch/benchmark/blob/3f146bbe7fdd65c6f4490993a8e0fa78c4465f37/torchbenchmark/models/pyhpc_turbulent_kinetic_energy/__init__.py#L124C5-L129C39
```python
class Model(BenchmarkModel):
    task = OTHER.OTHER_TASKS

    # Original input size: [2 ** i for i in range(12, 23, 2)]
    # Source: https://github.com/dionhaefner/pyhpc-benchmarks/blob/650ecc650e394df829944ffcf09e9d646ec69691/run.py#L25
    # Pick data-point when i = 20, size = 1048576
    DEFAULT_EVAL_BSIZE = 1048576
    ALLOW_CUSTOMIZE_BSIZE = False
    CANNOT_SET_CUSTOM_OPTIMIZER = True
```

I was trying to test these with [TorchDynamo Benchmark](https://github.com/pytorch/pytorch/tree/main/benchmarks/dynamo)

I was wondering, is there any specific reason for chosing that specific `batch_size` of $2^{20}$? Something to do with dynamo performance? 
In the `pyhpc_equation_of_state` we are allowed to make use of custom batch size, but for `pyhpc_turbulent_kinectic_energy` and cannot make use of custom batch size. Why is this difference?

**Comment by xuzhao9** [comment]
We did a sweep benchmarking across the original input sizes on PyTorch eager mode, and on A100 it reaches the highest tflops when i=20 with the eager mode.

**Comment by xuzhao9** [comment]
I think we had some issues with `pyhpc_turbulent_kinectic_energy ` when checking the numeric parity when changing the batch size. By default, if the model is able to change the batch size, the accuracy checking code will set the batch size to 4 to minimize the time needed to check the accuracy.
