### ISSUE TITLE
Unable to install with the latest `pip`

### ISSUE THREAD

**Issue by roastduck** [pytorch/benchmark#2239]
This is a dependency issue. See https://github.com/facebookresearch/detectron2/issues/4921. Either `pip<=22` or explicit `--no-build-isolation` in scripts in this repo (after explicitly installing some build-time dependencies) is required.

**Comment by xuzhao9** [comment]
Can you please pull the latest Docker image and check what is the pip version? 
https://github.com/pytorch/benchmark/pkgs/container/torchbench

**Comment by roastduck** [comment]
> Can you please pull the latest Docker image and check what is the pip version? https://github.com/pytorch/benchmark/pkgs/container/torchbench

It is pip 23.3.1 from miniconda. I was using pure Python. I think the behavior of pip in miniconda and in pure Python may be different.

**Comment by xuzhao9** [comment]
Since we assume python/pip/torch/torch* packages is already installed in the environment before running `python install.py`, we have no control of which pip version is installed on user's environment, and the only CI we have is the nightly docker. In the best effort we can add a warning about user's pip version, and I believe this is an issue that should be handled by detectron2 developers.

**Comment by roastduck** [comment]
If I understand correctly, detectron2 detects installed torch when installing, which cannot be done with build isolation. I think detectron2 developers may not be able to solve the problem unless by installing torch by themselves, but that will make the torch version inconsistent with ours.

Maybe explicitly disabling build isolation should be considered. I have successfully installed this repo with `PIP_NO_BUILD_ISOLATION=1` environment variable, but this is applied to all packaged this repo depends on. A better solution may be only disable build isolation for detectron2.

**Comment by xuzhao9** [comment]
@roastduck Can you please add the `PIP_NO_BUILD_ISOLATION=1` at https://github.com/pytorch/benchmark/blob/main/torchbenchmark/util/framework/detectron2/__init__.py#L46 and test? If it works, we can disable build isolation only for detectron2.

**Comment by roastduck** [comment]
It works and please find it in PR #2254.
