### ISSUE TITLE
fixture 'compiler' not found while executing "pytest test_bench.py"

### ISSUE THREAD

**Issue by yuxuan-z19** [pytorch/benchmark#2315]
I'm profiling the execution of BERT_pytorch with `test_bench.py` using PyTorch 2.0.1 with CUDA 11.7, in which the benchmark keeps updated to the [latest commit](https://github.com/pytorch/benchmark/commit/5f6633d3fbd7b8341f1314a3d87a0137eb8d9632). Scripts listed in README worked perfectly until I tried `test_bench.py`.

![image](https://github.com/pytorch/benchmark/assets/68550432/f7ae7dbe-fb2a-42ff-86ab-7e0982f70a08)

Python 3.10.12, and here are the packages I installed: [requirements.txt](https://github.com/user-attachments/files/15902499/requirements.txt)

Perhaps I missed something. Thanks!

**Comment by xuzhao9** [comment]
Hi @yuxuan-z19, can you please test on https://github.com/pytorch/benchmark/pull/2320 ?

**Comment by yuxuan-z19** [comment]
Thanks @xuzhao9 , it is working!

**Comment by yuxuan-z19** [comment]
Thanks @xuzhao9 , it's working!
