### ISSUE TITLE
Flop counter crashes with multiple compiled benchmarks

### ISSUE THREAD

**Issue by JasonMts** [pytorch/benchmark#2383]
When running several benchmarks with `run.py` in compile mode and attempting to collect flops metrics, the flop counter crashes complaining about multiple values for keyword argument 'out'.

Examples:

command:
`python benchmark/run.py hf_T5 -t train --metrics model_flops,cpu_peak_mem,ttfb --torchdynamo inductor`

output:
```
flop_count = flop_count_func(*args, **kwargs, out=out)  # type: ignore[operator]
TypeError: torch.utils.flop_counter.mm_flop() got multiple values for keyword argument 'out'
```

command:
`python benchmark/run.py torchrec_dlrm -t eval --metrics model_flops,cpu_peak_mem,ttfb --torchdynamo inductor`

output:
```
flop_count = flop_count_func(*args, **kwargs, out=out)  # type: ignore[operator]
TypeError: torch.utils.flop_counter.addmm_flop() got multiple values for keyword argument 'out'
```

Tests impacted include:
hf_GPT2_large, hf_T5, hf_T5_base, hf_T5_large, timm_vision_transformer_large, hf_GPT2_generate, hf_Yi, orca_2

It should be noted that metrics are collected fine if `model_flops` is not included.

Tested on:
Ubuntu 22.04.4 LTS
Python 3.10.12
torch 2.3.0+cpu
torchaudio 2.3.0+cpu
torchvision 0.18.0+cpu

**Comment by xuzhao9** [comment]
We are using the `__torch_dispatch__` based flops counter: https://dev-discuss.pytorch.org/t/the-ideal-pytorch-flop-counter-with-torch-dispatch/505.

I thought it works only in the eager mode and does not work with inductor. cc @Chillee

**Comment by Chillee** [comment]
Yeah, we need to disable `torch.compile` when running under the flop counter I think.

**Comment by xuzhao9** [comment]
@JasonMts Can you help try https://github.com/pytorch/benchmark/pull/2390 to see if it fixes the problem?
