### ISSUE TITLE
Failed TorchAO nightly workflow

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#2405]
https://github.com/pytorch/benchmark/actions/runs/10203374784/job/28229575495 failed because of missing the newly added config `huggingface.yaml`

**Comment by kit1980** [comment]
How do the commit get from pytorch to benchmark?

I see that the commit was copied https://github.com/pytorch/benchmark/commit/0dc03849bd93b4584a715239d5f55789e9ed214c , but it misses YAML from the original commit https://github.com/pytorch/pytorch/commit/8458980bbf78714a0fbe703785c100cad523fade

I will probably just add the YAML separately now.

**Comment by xuzhao9** [comment]
Internally we have ShipIt config to sync between pytorch/benchmarks/dynamo and benchmark/userbenchmark/dynamo/dynamobench, we need to change the config to sync the new files or sync the whole directory.
