### ISSUE TITLE
cpu pstate freq checking not working and setting not enabled

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#248]
Currently this check is failing on an ec2 machine that appears to have pstate freq pinned correctly on cores 0-47, but it complains about core 88

machine_config.py#L277

Suggest changing set/get pstate freq to use the `parse_lscpu_cpu_core_list` helper in the same file, so it can check the 'online' flag for each cpu and only get/set the min/max/curr freq for the online cpus.

and, make sure to set/get cpu freq _after_ disablling hyperthread, so that online list is accurate.

also, would be good to set pstate cpu freq when running with --configure flag (unless for some reason this isn't stable, then maybe add a comment about why)

**Comment by xuzhao9** [comment]
Address this issue in PR#250.
If we first disable HT, then pin the frequency, then the offline CPUs will remain in the old frequency. I don't think this will affect the online CPU cores' frequencies, but I don't find any driver documentation to support it either.

**Comment by xuzhao9** [comment]
Closed by PR#250.
