### ISSUE TITLE
v0 torchbench (and master) broken by BC change to torchtext

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#259]
fix both v0 and master branches so that both old and new torchtext works.  
 - try to import the old way, if it fails, try to import the new way

https://github.com/pytorch/text/commits/master

see this error 
ImportError: cannot import name 'TranslationDataset' from 'torchtext.datasets' (/home/ec2-user/anaconda3/envs/gh578224670/lib/python3.7/site-packages/torchtext/datasets/__init__.py)

from nightly CI
https://github.com/pytorch/benchmark/runs/1927202422?check_suite_focus=true

but look for any related imports of the other renamed packages, since the CI stopped at first failure.

**Comment by nikithamalgifb** [comment]
Now fixed in both master and v0. PR's for the fixes - #269, #266.  Closing this bug.
