### ISSUE TITLE
Several models do not honor the device flag

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#271]
These models silently use CPU in 'cuda' mode.  
![image](https://user-images.githubusercontent.com/4984825/108788830-be342a80-752d-11eb-901c-b670de16beb6.png)

**Comment by wconstab** [comment]
@Krovatkin filed to track

**Comment by desertfire** [comment]
Fixed by Nick in https://github.com/pytorch/benchmark/pull/274
