### ISSUE TITLE
Address dynamic shapes

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#276]
come up with a plan for benchmarking dynamic shapes.

Two issues we'll have to address to make this work
- identify a set of models we can use
- come up with a way to run enough steps that we are approaching the real dynamic-shape distribution in the full dataset, but without training to completion

@eellison Any thoughts on how to approach this?

**Comment by xuzhao9** [comment]
Added by https://github.com/pytorch/benchmark/pull/1914
