### ISSUE TITLE
[JIT not enabled] MOCO

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/benchmark#304]
See https://github.com/pytorch/benchmark/blob/master/torchbenchmark/models/moco/__init__.py#L73

**Comment by Krovatkin** [comment]
@wconstab do you happen to know by any chance why jit mode for MOCO was disabled?

**Comment by wconstab** [comment]
No, I don't know. if git blame shows it as part of my initial copy to this repo, you could check blame on the old repo which was pytorch/hub.  There could be some insight in the commit message.
