### ISSUE TITLE
BERT model misconfigured for training

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#317]
Batch Size and Sequence Length: The batch size (number of sequences) of 1 seems inappropriate for training along with a sequence length of 20. These seem like inference parameters as the benchmark is overloaded by allreduce communication, the optimizer, and CPU latency. I would suggest a minimum batch size of 32 with a sequence length of 128 (4096 total tokens). Bigger sequence lengths also expose improvements to multihead attention.

https://dev-discuss.pytorch.org/t/pytorch-benchmarks-issues-with-general-usability-and-issues-with-individual-benchmarks/169

**Comment by eircfb** [comment]
Fixed with

https://github.com/pytorch/benchmark/pull/434
