### ISSUE TITLE
Add a bunch of timm models

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#342]
https://github.com/rwightman/pytorch-image-models

pip install a specific version
then pick one or more models from the library based on popularity and interest, and wrap them in __init__

**Comment by xuzhao9** [comment]
Created https://github.com/pytorch/benchmark/pull/350 to add NFNet-F0 (DeepMind compatible) model to TorchBench. It should support other variants of the nfnet models as well.

**Comment by xuzhao9** [comment]
PR that adds a bunch of timm models: https://github.com/pytorch/benchmark/pull/352

**Comment by xuzhao9** [comment]
Closed by merging https://github.com/pytorch/benchmark/pull/352. Feel free to reopen it if people need more timm models.
