### ISSUE TITLE
demucs - gpu utilization may be too low

### ISSUE THREAD

**Issue by eircfb** [pytorch/benchmark#449]
Demucs time per test goes down when multiple copy streams are executed at the same time.

This can indicate that benchmark has too much idle time and will not be responsive to tools changes.

Test should have its data sizes checked.

streamcount, gpu time in ms:
1, 19.9744644
2, 13.226672
3, 12.40435133
4, 12.21978378
5, 11.82586898
6, 11.64228817
7, 11.59060123
8, 11.63492393
9, 11.601938
10, 11.562163

**Comment by xuzhao9** [comment]
Fixed in https://github.com/pytorch/benchmark/pull/639.
