### ISSUE TITLE
learningtopaint - gpu utilization may be too low

### ISSUE THREAD

**Issue by eircfb** [pytorch/benchmark#450]
learningtopaint gpu time per test goes down when multiple copy streams are executed at the same time.

This can indicate that benchmark has too much idle time and will not be responsive to tools changes.

Test should have its data sizes checked.

streamcount, gpu time in ms:
1, 2.132096052
2, 1.758159995
3, 1.696522713
4, 1.836799979
5, 1.737471962
6, 1.777754625
7, 1.755195481
8, 1.718631983
9, 1.776046223
10, 1.69311676

**Comment by xuzhao9** [comment]
The GPU utilization issue is because of bad model code. Therefore, we are not fixing it to be faithful to the original model performance.
