### ISSUE TITLE
benchmark/rnns/benchmarks/lstm_variants/lstm.py equation error

### ISSUE THREAD

**Issue by bapalto** [pytorch/benchmark#55]
I think in line 192 in file benchmark/rnns/benchmarks/lstm_variants/lstm.py

o_t = gates[:, -self.hidden_size:]

should be modified to 

o_t = gates[:, 2 * self.hidden_size:3 * self.hidden_size]

**Comment by soumith** [comment]
cc: @zou3519 if you remember.

**Comment by bapalto** [comment]
Sorry, I was mistaken, both solutions are correct.
