### ISSUE TITLE
tacotron2: train/eval/example disabled on CUDA

### ISSUE THREAD

**Issue by aaronenyeshi** [pytorch/benchmark#612]
After aligning the tacotron2's parameters to match with the source paper and source code (such as batch size), the tests for train, eval, and example run into `RuntimeError: CUDA out of memory.` due to CI's Tesla T4 GPU.

Aligned with Source: https://github.com/pytorch/benchmark/pull/610

Failed Tests due to `RuntimeError: CUDA out of memory.`:
- test_tacotron2_train_cuda
- test_tacotron2_example_cuda
- test_tacotron2_eval_cuda

TODO: Re-enable these tests once the CI upgrades the GPU.

**Comment by xuzhao9** [comment]
Fixed by https://github.com/pytorch/benchmark/pull/781
