### ISSUE TITLE
The test code, which tests the correctness of FastRnn, allows small difference between the output of FastRnn and the output of cudnn's rnn

### ISSUE THREAD

**Issue by SamChen** [pytorch/benchmark#62]
Hi, 

First, I want to thank you guys for sharing the code. I learned a lot from it. It gives me a good start for implement my own GRU layer.   :-)

One thing that I am very confusing is the outputs from cudnn's lstm and the fastrnn's lstm are different. Based on the assertions in [your test code](https://github.com/pytorch/benchmark/blob/877113367236968470e5694a4f1343e5654c11bd/rnns/fastrnns/custom_lstms.py#L398-L400), I guess it is a common case which I do not need to worry too much. But, I am curious what cause the difference. 

Thanks for your time :-)

**Comment by xuzhao9** [comment]
Closed as they are not relevant anymore.
