### ISSUE TITLE
TODO: Update test_bench.py and test.py to use the same EXCLUDELIST to skip tests

### ISSUE THREAD

**Issue by aaronenyeshi** [pytorch/benchmark#626]
Create a central EXCLUDELIST that contains all the tests that need to be skipped, and share the same list between test.py and test_bench.py.

At the moment, we only have the list in test.py. This will allow us to have a clear list of skipped tests.

**Comment by xuzhao9** [comment]
Fixed by https://github.com/pytorch/benchmark/pull/781
