### ISSUE TITLE
Gate CUDA failures behind some kind of flag?

### ISSUE THREAD

**Issue by Chillee** [pytorch/benchmark#688]
Currently, a bunch of models error when you call `get_module()` due to CI reasons. However, if you have an A100 they run perfectly fine. So, it's a bit annoying to need to modify the benchmarks a ton just to get a model that should work on your GPU.

**Comment by xuzhao9** [comment]
Good point, I think we should have an abstract layer to determine what tests (and configurations) are available given the current user platform.
