### ISSUE TITLE
Support for different Python versions

### ISSUE THREAD

**Issue by kit1980** [pytorch/benchmark#691]
I wonder what's the long-term plan to support new Python versions?

As a concrete example, currently it's not possible to install benchmark on Python 3.9 as is:
demucs has a dependency on lameenc==1.2.2, which is not available on Python 3.9.

So when Python 3.9 needs to be supported, will older models that can't be run with 3.9 be just removed (or maybe updated)?
Or should there be a mechanism to only install what is supported - different set of models for different Python versions, possibly with different version of dependencies?

**Comment by xuzhao9** [comment]
I believe the long-term goal is to keep models updated for the Python versions we support. For example, when we decide to support Python 3.9, we should update demucs model (or remove it, if it can't be fixed).
