### ISSUE TITLE
Audit existing models

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#70]
First, create a checklist of important things for each model

Then go through each model and make sure they comply

**Comment by Krovatkin** [comment]
I will be editing this list as I come up with more checks:

[ ] Make sure that device and jit are routed to model's c-tors so a model actually runs on the right device and in the right mode (i.e. jit). This could be verified by simply checking the model's inputs and outputs. This could be automated.
[ ] **Double check** that in `test_eval` a model is running under `no_grad` and `eval` is called. we could automatically check that all model paratemeters don't require gradients and inputs.
[ ] Consider running a model under `autograd.profiler` and look for gaps in between events as gaps signify that we are doing extra work (constructing a model from scratch in every eval run) that's not relevant to model execution. (Note, optimizers do show up as a series of events) 
[ ] If the model is jittable, consider enabling `check_results` for the model
[ ] Consider provided the frozen version of the model
