### ISSUE TITLE
scribe.py fails to upload result to rds

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#710]
In the V2 score, we updated the score schema to include by-domain subscores.
This change seems to break `scribe.py` which uploads the results to rds (https://github.com/pytorch/benchmark/blob/main/scripts/upload_scribe_v2.py#L50).
Example failed workflow: https://github.com/pytorch/benchmark/runs/4937888834?check_suite_focus=true

So currently, I have disabled the rds upload in v2.

**Comment by xuzhao9** [comment]
@janeyx99 , do you still need to upload the metrics to the DB behind `https://metrics.pytorch.org`?

**Comment by janeyx99** [comment]
It is fine to not upload through RDS as long as it's backed somewhere. We are in the process of migrating from using RDS to Rockset so this isn't a big issue.
