### ISSUE TITLE
timm_efficientdet prints out spam while loading

### ISSUE THREAD

**Issue by jansel** [pytorch/benchmark#840]
```
./torchbench.py -k timm_efficientdet --nothing
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
```

Loading a module should not print.

**Comment by xuzhao9** [comment]
These are printed by a dependency of the model, pycocotools: https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py#L82, we can disable these printing statements by patching the package.
