### ISSUE TITLE
Remove tacotron2 model

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#867]
I propose we remove the [tacotron2](https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models/tacotron2) model because:
1. the last update time to this model is ~2 years ago, which seems it has stopped development;
2. it hard depends on [librosa](https://github.com/NVIDIA/tacotron2/blob/master/requirements.txt#L5), which depends on [numba](https://pypi.org/project/numba/) and [numpy < 1.22](https://pypi.org/project/numba/). This breaks the current pytorch numpy api compatibility.

**Comment by xuzhao9** [comment]
I think we should pin numpy version instead of removing this model.

**Comment by jansel** [comment]
How hard would it be to upgrade that dependency?  What breaks if we upgrade it?
