### ISSUE TITLE
Add PyText model to benchmark repo

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#92]
We're building a suite of pytorch benchmarks by forking popular open-source models and modifying them to conform to a common API that facilitates a central tool installing, running, and collecting measurements.

Benchmark Repo: https://github.com/pytorch/benchmark
Instructions: https://github.com/pytorch/benchmark/blob/master/torchbenchmark/models/ADDING_MODELS.md
Source model: https://github.com/facebookresearch/pytext

After finishing the install.py and __init__.py, prep a github PR for review.

**Comment by xuzhao9** [comment]
Closing the issue since there has been no active development in the pytest repo. We should add models from fairseq repo instead.
