### ISSUE TITLE
Add StarGAN model to benchmark repo

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#93]
We're building a suite of pytorch benchmarks by forking popular open-source models and modifying them to conform to a common API that facilitates a central tool installing, running, and collecting measurements.

Benchmark Repo: https://github.com/pytorch/benchmark
Instructions: https://github.com/pytorch/benchmark/blob/master/models/ADDING_MODELS.md
Source model: https://github.com/zou3519/stargan

The StarGAN model has already been forked and modified in a previous phase of this process, but the API (install.py, hubconf.py) had not yet been standardized.  Copy the repo below and follow the latest instructions in the playbook to add the new API.  Note, the 'install.sh' and 'run.sh' scripts added in the previous effort would serve as good hints on how to proceed.

note in this case it looks like there are no steps to do for installation, but the install.py file should still be present as a no-op for the API sake.

**Comment by EdwardTyantov** [comment]
@wconstab pls review PR
