### ISSUE TITLE
NVFuser is the default fuser for Nvidia GPU now

### ISSUE THREAD

**Issue by LSC527** [pytorch/benchmark#956]
Codes for switching fuser need to be updated.

**Comment by xuzhao9** [comment]
@LSC527 Thanks for raising this issue. By default we are not applying any fuser to the model, and users can specify their fusers using the option `--fuser` (https://github.com/pytorch/benchmark/blob/main/torchbenchmark/util/extra_args.py#L92). Could you clarify on how should we update the code for switching fuser?

**Comment by LSC527** [comment]
```python run.py``` looks good and needs no update. But ```pytest test_bench.py``` config fuser option in ```confest.py``` and did nothing when fuser is the default "te". This seems to enable nvfuser by default.
https://github.com/pytorch/benchmark/blob/f30d537c95702b59515c6d65c99e1b0f41ecd994/conftest.py#L24

**Comment by xuzhao9** [comment]
Please help review https://github.com/pytorch/benchmark/pull/963, thanks!
