### ISSUE TITLE
unify the approach to train() and eval() implementation

### ISSUE THREAD

**Issue by wconstab** [pytorch/benchmark#99]
some models implement by preparing data, .cuda() etc. in __init__ and do the bare minimum 'inner loop' in train()/eval() - this plays nicely with the benchmark setup.

Other models may use vanilla 'training_loop' functions from original model code, and call this from train() or eval(), which means  we could be benchmarking more overhead than we want. 

Audit the existing models and identify which ones if any are problematic, address them.

**Comment by xuzhao9** [comment]
We have audited all the models to use the bare minimum train/eval approach.
